# Generated by Django 3.0.5 on 2020-05-27 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_auto_20200526_0716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='group_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='group_specialization',
            new_name='specialization',
        ),
    ]
