# Generated by Django 3.0.5 on 2020-05-10 12:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_auto_20200510_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='birthdate',
            field=models.DateField(default=datetime.datetime(2020, 5, 10, 12, 15, 58, 993642)),
        ),
    ]
