# Generated by Django 3.0.5 on 2020-05-24 07:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_auto_20200516_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='birthdate',
            field=models.DateField(default=datetime.datetime(2020, 5, 24, 7, 58, 22, 690351)),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
