# Generated by Django 2.2.3 on 2020-06-10 17:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0017_auto_20200527_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='birthdate',
            field=models.DateField(default=datetime.datetime(2020, 6, 10, 17, 10, 45, 166451)),
        ),
    ]
