# Generated by Django 3.0.5 on 2020-05-26 07:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_auto_20200524_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='birthdate',
            field=models.DateField(default=datetime.date(2020, 5, 26)),
        ),
    ]
